#!/usr/bin/env ruby

require 'nmon_commands'
require 'optimist'


opts = Options.new

files = NmonCommands.get_file_list(opts.customer, opts.uuid)

files = NmonCommands.filter_by_dates(files,opts.start,opts.end)

data  = NmonCommands.get(files)

ap data
